### ISSUE TITLE
Improve link checking between depenizen and depenizenBungee

### ISSUE THREAD

**Issue by Anduril31** [DenizenScript/DepenizenBungee#2]
Hi,

After several tests, it seems to me that Depenizen and DepenizenBungee could be updated in terms of checking the link between the spigot server and bungee. Currently, the DepenizenBungee checks that the ip indicated in the Depenizen configuration file of the spigot server is strictly equal to the address of the bungee server.

https://github.com/DenizenScript/DepenizenBungee/blob/eba1718622e3183b5ceec6634070eb48b32dcd54/src/main/java/com/denizenscript/depenizen/bungee/DepenizenBungee.java#L233

In certain contexts, for example in a Docker architecture, this verification is sometime not possible for reasons of network architecture that we do not master (server rental). 

I think that adding a token to "authenticate" the connection between the bungee server and spigot would be a good idea. In case of failure of the IP verification, the verification of the token would take over and Depenizen and DepenizenBungee would no longer be dependent on the network architecture.

**Comment by mcmonkey4eva** [comment]
There is no possible situation in which you can't know the connection address from one server to another, other than if the address dynamically changes, which is **never** okay to happen in a server environment (and, even if they did change dynamically... if your Bungee server still works, it means you already have the logic in place to automatically correct the address, which would automatically apply to DepenizenBungee as well).

It's possible you simply don't know the correct address or have mistakenly set an indirect path address rather than the direct path address, in which case it's a very simple matter of changing to the correct address.

If you look in your logs, whatever IP address attempts and then fails to connect to DepenizenBungee, is the actual correct address for that server, and is the one you should have in your bungee config. Any other addresses, even if they work, are alias addresses or indirect addresses (this commonly happens with eg users typing in the remote/global IP address for a server, but the servers are localhosted or on LAN, and so there is a localhost or LAN address that is more direct and therefore is the _real_ path that should be used for everything internal) (note also that bungee servers very much do only use internal connections, and you should have the internal address in use, and the Spigot sub-servers should in fact be *blocked* from external connections entirely, allowing ONLY internal connections).

**Comment by Anduril31** [comment]
I'm not sure it's that simple. My web host (Minestrator) uses Pterodactyl and the page below explains the problem I am having.

[https://pterodactyl.io/community/games/minecraft.html#configuring-a-server-network-bungeecord-waterfall-hexacord-etc ](https://pterodactyl.io/community/games/minecraft.html#configuring-a-server-network-bungeecord-waterfall-hexacord-etc )

There are several network layers on this architecture and an IP check cannot be done because of network layer changes.

BungeeGuard works perfectly and uses a token system (https://github.com/lucko/BungeeGuard). Thanks to this, it does not depend on the architecture of the servers.

**Comment by mcmonkey4eva** [comment]
If the most direct connection address is changing arbitrarily, that is a configuration error of some form that must be addressed.
There is no valid architecture for a bungee network with unpredictable network addresses.

Support and help with Denizen and related projects is on Discord @ https://discord.gg/Q6pZGSR
